mysql:
  host: cd-cdb-3w8ntur2.sql.tencentcdb.com
  port: 62626
  user: root
  password: root123456

redis:
  host: 111.229.58.109
  port: 6379
  user: root
  password: root123456
  db: 0

mongo:
  host: 111.229.58.109
  port: 27017
  user: "root"
  password: "123456"
  db: "test"
  auth_source: ""
